# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiF9H20eyo1i1v-xeVE_V2uZSptTxW7X
"""

from google.colab import files
uploaded = files.upload()

text_column = "Text"
target_column = "Category"

import pandas as pd
import pickle
import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

df = pd.read_json("resumes_dataset.jsonl", lines=True)

print("Columns:", df.columns.tolist())

text_column = "Text"
target_column = "Category"

if text_column not in df.columns:
    raise ValueError(f"{text_column} not found. Available: {df.columns.tolist()}")

if target_column not in df.columns:
    raise ValueError(f"{target_column} not found. Available: {df.columns.tolist()}")

df = df[[text_column, target_column]].copy()
df = df.dropna()
df = df.drop_duplicates()

print("Shape before filtering:", df.shape)
print("\nCategory counts:\n")
print(df[target_column].value_counts())

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df[text_column] = df[text_column].apply(clean_text)

label_counts = df[target_column].value_counts()
valid_labels = label_counts[label_counts >= 5].index
df = df[df[target_column].isin(valid_labels)].copy()

print("\nShape after filtering:", df.shape)
print("\nCategory counts after filtering:\n")
print(df[target_column].value_counts())

X = df[text_column]
y = df[target_column]

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True,
    stop_words="english"
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

models = {
    "LinearSVC": LinearSVC(class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=3000, class_weight="balanced"),
    "MultinomialNB": MultinomialNB()
}

best_model = None
best_model_name = None
best_accuracy = 0
best_f1 = 0
best_preds = None

print("\nMODEL RESULTS\n")

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    preds = model.predict(X_test_vec)

    acc = accuracy_score(y_test, preds)
    f1 = f1_score(y_test, preds, average="macro")

    print("Model:", name)
    print("Accuracy:", acc)
    print("F1 Macro:", f1)
    print("-" * 40)

    if f1 > best_f1:
        best_f1 = f1
        best_accuracy = acc
        best_model = model
        best_model_name = name
        best_preds = preds

print("\nBest Model:", best_model_name)
print("Best Accuracy:", best_accuracy)
print("Best F1 Macro:", best_f1)

print("\nClassification Report:\n")
print(classification_report(y_test, best_preds, target_names=label_encoder.classes_))

# Save
with open("resume_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

with open("resume_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

with open("resume_label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

print("\nSaved successfully")

def predict_resume_category(resume_text):
    cleaned = clean_text(resume_text)
    vec = vectorizer.transform([cleaned])
    pred = best_model.predict(vec)
    return label_encoder.inverse_transform(pred)[0]

sample_resume = """
Python, machine learning, data analysis, pandas, numpy, SQL,
built predictive models and dashboards, worked on analytics projects
"""

print("Predicted Category:", predict_resume_category(sample_resume))

print(df.columns.tolist())

print(predict_resume_category("""
Python, machine learning, deep learning, pandas, numpy,
scikit-learn, data analysis, statistics, SQL, data visualization,
worked on predictive models and classification problems
"""))

print(predict_resume_category("""
Human resource management, recruitment, talent acquisition,
employee relations, onboarding, payroll, HR policies,
training and development
"""))

print(predict_resume_category("""
Accounting, financial analysis, balance sheet,
income statement, auditing, taxation, Excel,
financial reporting, budgeting
"""))

res = predict_resume_category("python machine learning data analysis")
print("Predicted:", res)