# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cd8FGpOR6XXrNN-r52KLih1QRFt1o5Tk
"""

import pandas as pd
import pickle
import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression


df = pd.read_csv("dataset (1).csv")

df.columns = df.columns.str.strip()

def clean_column_name(col):
    col = col.strip().lower()
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col)
    return col.strip("_")

df.columns = [clean_column_name(col) for col in df.columns]

print("Cleaned columns:")
print(df.columns.tolist())


target_column = "target"

if target_column not in df.columns:
    raise ValueError("Target column nahi mili. Column names check karo.")

print("\nMissing values before filling:")
print(df.isnull().sum())

print("\nDuplicate rows before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicate rows after:", df.duplicated().sum())

df[target_column] = df[target_column].replace({
    "Dropout": 1,
    "Enrolled": 1,
    "Graduate": 0
})

print("\nTarget value counts after conversion:")
print(df[target_column].value_counts())


df[target_column] = pd.to_numeric(df[target_column], errors="coerce")


df = df.dropna(subset=[target_column])

X = df.drop(target_column, axis=1)
y = df[target_column]

numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object", "category", "bool"]).columns.tolist()

print("\nNumeric columns:", numeric_features)
print("\nCategorical columns:", categorical_features)

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

models = {
    "RandomForest": RandomForestClassifier(
        n_estimators=300,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        class_weight="balanced"
    ),
    "ExtraTrees": ExtraTreesClassifier(
        n_estimators=300,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        class_weight="balanced"
    ),
    "LogisticRegression": LogisticRegression(
        max_iter=5000,
        class_weight="balanced"
    )
}

best_model_name = None
best_pipeline = None
best_accuracy = 0
best_f1 = 0
best_preds = None

print("\n========== MODEL RESULTS ==========\n")

for name, model in models.items():
    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", model)
    ])

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(name)
    print("Accuracy:", acc)
    print("F1 Score:", f1)
    print("-" * 40)

    if f1 > best_f1:
        best_f1 = f1
        best_accuracy = acc
        best_model_name = name
        best_pipeline = pipeline
        best_preds = y_pred

print("\n========== BEST MODEL ==========\n")
print("Best Model:", best_model_name)
print("Best Accuracy:", best_accuracy)
print("Best F1 Score:", best_f1)

print("\nClassification Report:")
print(classification_report(y_test, best_preds))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, best_preds))

df.to_csv("cleaned_academic_dataset.csv", index=False)
print("\nCleaned dataset saved as cleaned_academic_dataset.csv")

with open("academic_risk_model.pkl", "wb") as f:
    pickle.dump(best_pipeline, f)

with open("model_columns.pkl", "wb") as f:
    pickle.dump(X.columns.tolist(), f)

print("Best model saved as academic_risk_model.pkl")
print("Columns saved as model_columns.pkl")

sample = pd.DataFrame([{
    'marital_status': 1,
    'application_mode': 1,
    'application_order': 1,
    'course': 171,
    'daytime_evening_attendance': 1,
    'previous_qualification': 1,
    'nacionality': 1,
    'mother_s_qualification': 19,
    'father_s_qualification': 19,
    'mother_s_occupation': 5,
    'father_s_occupation': 5,
    'displaced': 0,
    'educational_special_needs': 0,
    'debtor': 0,
    'tuition_fees_up_to_date': 1,
    'gender': 1,
    'scholarship_holder': 1,
    'age_at_enrollment': 18,
    'international': 0,
    'curricular_units_1st_sem_credited': 0,
    'curricular_units_1st_sem_enrolled': 6,
    'curricular_units_1st_sem_evaluations': 6,
    'curricular_units_1st_sem_approved': 6,
    'curricular_units_1st_sem_grade': 14,
    'curricular_units_1st_sem_without_evaluations': 0,
    'curricular_units_2nd_sem_credited': 0,
    'curricular_units_2nd_sem_enrolled': 6,
    'curricular_units_2nd_sem_evaluations': 6,
    'curricular_units_2nd_sem_approved': 6,
    'curricular_units_2nd_sem_grade': 15,
    'curricular_units_2nd_sem_without_evaluations': 0,
    'unemployment_rate': 10.5,
    'inflation_rate': 1.2,
    'gdp': 1.5
}])

print("Prediction:", best_pipeline.predict(sample))

proba = best_pipeline.predict_proba(sample)
print("Confidence:", proba)

sample = X_test.iloc[[0]]
print("Actual:", y_test.iloc[0])
print("Predicted:", best_pipeline.predict(sample)[0])

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

param_grid = {
    "classifier__n_estimators": [300, 500, 700],
    "classifier__max_depth": [10, 15, 20, None],
    "classifier__min_samples_split": [2, 5, 10],
    "classifier__min_samples_leaf": [1, 2, 4]
}

grid = GridSearchCV(
    best_pipeline,
    param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

grid.fit(X_train, y_train)

best_pipeline = grid.best_estimator_
y_pred = best_pipeline.predict(X_test)

print("Best Params:", grid.best_params_)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Columns saved as model_columns.pkl")