# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WUxUAMaSP1oCXkQ6KBwaSi29nPhcQhP
"""

!pip -q install catboost

from google.colab import files
uploaded = files.upload()

import pandas as pd
import pickle
import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

df = pd.read_csv("Tech_Data_Cleaned.csv")

def clean_column_name(col):
    col = col.strip().lower()
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col)
    return col.strip("_")

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df.columns = [clean_column_name(c) for c in df.columns]
df = df.fillna("unknown")

target_column = "field"

if target_column not in df.columns:
    raise ValueError(f"Target column '{target_column}' not found. Available columns: {df.columns.tolist()}")

print("Columns:", df.columns.tolist())
print("\nOriginal shape:", df.shape)
print(f"\n{target_column} counts:\n")
print(df[target_column].value_counts())

feature_cols = [col for col in df.columns if col != target_column]

for col in feature_cols:
    df[col] = df[col].astype(str).apply(clean_text)

df["combined_text"] = df[feature_cols].astype(str).apply(lambda row: " ".join(row), axis=1)

X = df["combined_text"]
y = df[target_column]

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.95,
    sublinear_tf=True
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

models = {
    "LinearSVC": LinearSVC(class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=3000, class_weight="balanced"),
    "MultinomialNB": MultinomialNB()
}

best_model = None
best_model_name = None
best_accuracy = 0
best_f1 = 0
best_preds = None

print("\n========== MODEL RESULTS ==========\n")

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    preds = model.predict(X_test_vec)

    acc = accuracy_score(y_test, preds)
    f1 = f1_score(y_test, preds, average="macro")

    print(name)
    print("Accuracy:", acc)
    print("F1 Macro:", f1)
    print("-" * 40)

    if f1 > best_f1:
        best_f1 = f1
        best_accuracy = acc
        best_model = model
        best_model_name = name
        best_preds = preds

print("\n========== BEST MODEL ==========\n")
print("Best Model:", best_model_name)
print("Best Accuracy:", best_accuracy)
print("Best F1 Macro:", best_f1)

print("\nClassification Report:\n")
print(classification_report(y_test, best_preds, target_names=label_encoder.classes_))

with open("career_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

with open("career_label.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

with open("career_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("\nBest model saved successfully")

def predict_role(input_dict):

    text = " ".join([str(v).lower() for v in input_dict.values()])


    text_vec = vectorizer.transform([text])


    pred = best_model.predict(text_vec)


    result = label_encoder.inverse_transform(pred)

    return result[0]

sample_input = {
    "subfields": "machine learning artificial intelligence",
    "job_roles": "",
    "programming_languages": "python",
    "tools": "tensorflow pytorch",
    "skills": "deep learning data analysis",
    "educational_background": "btech computer science"
}

print("Predicted:", predict_role(sample_input))